### ISSUE TITLE
OSError: [Errno 2] No such file or directory picard

### ISSUE THREAD

**Issue by jferrerobiol** [faircloth-lab/radcap#2]
Dear Brant,
I am analysing Radcap data and we are trying to use radcap for it. I was able to run the radcap_prepare_sample_directories.py without any problem but when trying to run radcap_snp_bwa_align.py I got the following error:

Traceback (most recent call last):
  File "/users/jferrer/programari/radcap-master/bin/radcap_snp_bwa_align.py", line 20, in <module>
    from radcap import picard
  File "/users/jferrer/programari/anaconda2/lib/python2.7/site-packages/radcap/picard.py", line 17, in <module>
    from phyluce.pth import get_user_path, get_user_param
  File "/users/jferrer/programari/anaconda2/lib/python2.7/site-packages/phyluce/__init__.py", line 16, in <module>
    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
  File "/users/jferrer/programari/anaconda2/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/users/jferrer/programari/anaconda2/lib/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

I imagine that it is some kind of error linked with picard tools, probably it does not find them? Do you have any ideas about what is probably happening?

Thank you very much for your help and apologize for the inconvenience.

Joan

**Comment by brantfaircloth** [comment]
Hi Joan,

I just edited the code to update the line in `picard.py` (https://github.com/faircloth-lab/radcap/blob/master/radcap/picard.py#L17) hopefully that will fix the issue.  If you run `git pull` you should get the changes.

**Comment by jferrerobiol** [comment]
Hi Brant,
Thank you very much for your rapid answer. It works fine right now!

**Comment by jferrerobiol** [comment]
Hi Brant,
I have realized that the same change had to be done in gatk.py. I have been running through the pipeline without any problems but I got stuck when trying to run radcap_call_snps.py by the following error:

Traceback (most recent call last):
  File "/users/jferrer/programari/radcap-master/bin/radcap_call_snps.py", line 108, in <module>
    main()
  File "/users/jferrer/programari/radcap-master/bin/radcap_call_snps.py", line 94, in main
    with open(filtered_variants_vcf, 'r') as infile:
IOError: [Errno 2] No such file or directory: '/users/jferrer/Fer/GuttatusRadCap_Barcelona/Guttatus_s
nps/guttatus_bams.merged.bam.realigned.bam.filtered-variants.vcf'

I have noticed that it stopped when trying to create a file of PASSING SNP calls. When checking the gatk log files, there has been an error running GATK:

##### ERROR stack trace 
java.lang.ExceptionInInitializerError
	at org.broadinstitute.sting.gatk.GenomeAnalysisEngine.<init>(GenomeAnalysisEngine.java:160)
	at org.broadinstitute.sting.gatk.CommandLineExecutable.<init>(CommandLineExecutable.java:53)
	at org.broadinstitute.sting.gatk.CommandLineGATK.<init>(CommandLineGATK.java:54)
	at org.broadinstitute.sting.gatk.CommandLineGATK.main(CommandLineGATK.java:90)
Caused by: java.lang.NullPointerException
	at org.reflections.Reflections.scan(Reflections.java:220)
	at org.reflections.Reflections.scan(Reflections.java:166)
	at org.reflections.Reflections.<init>(Reflections.java:94)
	at org.broadinstitute.sting.utils.classloader.PluginManager.<clinit>(PluginManager.java:77)
	... 4 more

I would really appreciate your feedback on the error.
Thank you very much and apologize for the inconvenience.

**Comment by brantfaircloth** [comment]
possibly a java version issue.  depending on which java you have installed you may need 1.6 or 1.7... that can cause problems that look like this...

**Comment by jferrerobiol** [comment]
That was it! With java 1.7 works perfectly fine. Thank you very much Brant and apologize for the inconvenience.
