### ISSUE TITLE
call_snp

### ISSUE THREAD

**Issue by Ferxengutta** [faircloth-lab/radcap#3]
Bear Brant.

I was working with the RADCap pipeline, but just when I tried to use call_snp, have next error. I've changed the path for radcap.

Do you have any idea?

Best regards

File "/users/jferrer/programari/radcap-master/bin/radcap_call_snps.py", line 108, in <module>
    main()
  File "/users/jferrer/programari/radcap-master/bin/radcap_call_snps.py", line 94, in main
    with open(filtered_variants_vcf, 'r') as infile:
IOError: [Errno 2] No such file or directory: '/users/jferrer/Fer/GuttatusRadCap_Barcelona/Guttatus_snps2/guttatus_bams.merged.bam.realigned.bam.filtered-variants.vcf'

**Comment by crisale84** [comment]
Hi Brant
I'm trying to work with radcap, but theres no documentation of installing, and then it has next errors :
¿some advice?

$python bin/radcap_snp_bwa_align.py --config ./config/radcap.conf  --output ~/radcap.faircloth/GATK-aligned --cores 4 --bwa-mem
Traceback (most recent call last):
  File "bin/radcap_snp_bwa_align.py", line 19, in <module>
    from radcap import bwa
  File "/Users/cristinadominguez/miniconda2/lib/python2.7/site-packages/radcap/bwa.py", line 21, in <module>
    JAVA = get_user_param("java", "executable")
  File "/Users/cristinadominguez/miniconda2/lib/python2.7/site-packages/radcap/pth.py", line 44, in get_user_param
    return config.get(section, param)
  File "/Users/cristinadominguez/miniconda2/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'java'
